### ISSUE TITLE
[Build Pipeline] Add context parameter for correct component directory in pipeline

### ISSUE THREAD

**Issue by guimoreirar** [LerianStudio/midaz#873]

**Comment by guimoreirar** [comment]
https://github.com/marketplace/actions/build-and-push-docker-images#path-context

**Comment by guimoreirar** [comment]
from:

# Build and push multi-architecture Docker images
```
      - name: Build and Push Docker image (Multi-Arch)
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.app.working_dir }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
```


to:

# Build and push multi-architecture Docker images
```
      - name: Build and Push Docker image (Multi-Arch)
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.app.working_dir }}
          file: ${{ matrix.app.working_dir }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
```

The Docker build context is incorrectly set to the root of the repository (.) instead of the component’s folder. The COPY command expects files relative to the build context, not the Dockerfile location.
